/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Personal
 */
public class Interfaz1 extends javax.swing.JFrame {
    
    /**
     * Creates new form Interfaz1
     */
    public Interfaz1() {
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        bienvenida1 = new javax.swing.JLabel();
        cantFilas = new javax.swing.JLabel();
        cantColumnas = new javax.swing.JLabel();
        cantMinas = new javax.swing.JLabel();
        numFilas = new javax.swing.JTextField();
        numColumnas = new javax.swing.JTextField();
        numMinas = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        generarTablero = new javax.swing.JButton();
        barrer = new javax.swing.JButton();
        ponerBandera = new javax.swing.JButton();
        casilla = new javax.swing.JTextField();
        quitarBandera = new javax.swing.JButton();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        metodoBFS = new javax.swing.JRadioButton();
        metodoDFS = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("BuscaMinas");

        bienvenida1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bienvenida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenida1.setText("Bienvenido al juego Busca Minas, por favor ingrese el tamaño del tablero y la cantidad de minas.");

        cantFilas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantFilas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantFilas.setText("Cant. de filas:");

        cantColumnas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantColumnas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantColumnas.setText("Cant. de columnas:");

        cantMinas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantMinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantMinas.setText("Cant. de minas:");

        numFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numFilasActionPerformed(evt);
            }
        });

        numColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numColumnasActionPerformed(evt);
            }
        });

        numMinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMinasActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        generarTablero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generarTablero.setText("Generar tablero");
        generarTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarTableroActionPerformed(evt);
            }
        });

        barrer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barrer.setText("Barrer Casilla");
        barrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barrerActionPerformed(evt);
            }
        });

        ponerBandera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ponerBandera.setText("Poner Bandera");
        ponerBandera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerBanderaActionPerformed(evt);
            }
        });

        casilla.setText("Casilla");
        casilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casillaActionPerformed(evt);
            }
        });

        quitarBandera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quitarBandera.setText("Quitar Bandera");
        quitarBandera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarBanderaActionPerformed(evt);
            }
        });

        texto2.setText("Especificar casilla:");

        texto3.setText("Marcar método de búsqueda:");

        metodoBFS.setText("Breadth-First Search");
        metodoBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoBFSActionPerformed(evt);
            }
        });

        metodoDFS.setText("Depth-First Search");
        metodoDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoDFSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bienvenida1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cantFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(cantColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(cantMinas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numMinas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(quitarBandera)
                                        .addGap(18, 18, 18)
                                        .addComponent(ponerBandera)
                                        .addGap(18, 18, 18)
                                        .addComponent(barrer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(generarTablero))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(casilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texto3)
                                    .addComponent(metodoBFS)
                                    .addComponent(metodoDFS))))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bienvenida1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantFilas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantColumnas)
                    .addComponent(cantMinas)
                    .addComponent(numMinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(texto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(texto3)
                .addGap(18, 18, 18)
                .addComponent(metodoBFS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(metodoDFS)
                .addGap(280, 280, 280)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(guardar)
                    .addComponent(generarTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitarBandera, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponerBandera)
                    .addComponent(barrer))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numFilasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numFilasActionPerformed

    private void numColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numColumnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numColumnasActionPerformed

    private void numMinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMinasActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void generarTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarTableroActionPerformed
        // TODO add your handling code here:
        //Guardamos los datos ingresados en los textField en una variable usando el getText(), el cual retorna String por defecto.
        int nFilas = Integer.parseInt(numFilas.getText());
        int nColumnas = Integer.parseInt(numColumnas.getText());
        int nMinas = Integer.parseInt(numMinas.getText());
    }//GEN-LAST:event_generarTableroActionPerformed

    private void casillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casillaActionPerformed

    private void barrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barrerActionPerformed

    private void ponerBanderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerBanderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponerBanderaActionPerformed

    private void quitarBanderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarBanderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitarBanderaActionPerformed

    private void metodoBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoBFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodoBFSActionPerformed

    private void metodoDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoDFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodoDFSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
                
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barrer;
    private javax.swing.JLabel bienvenida1;
    private javax.swing.JLabel cantColumnas;
    private javax.swing.JLabel cantFilas;
    private javax.swing.JLabel cantMinas;
    private javax.swing.JTextField casilla;
    private javax.swing.JButton exit;
    private javax.swing.JButton generarTablero;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton metodoBFS;
    private javax.swing.JRadioButton metodoDFS;
    private javax.swing.JTextField numColumnas;
    private javax.swing.JTextField numFilas;
    private javax.swing.JTextField numMinas;
    private javax.swing.JButton ponerBandera;
    private javax.swing.JButton quitarBandera;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
